FROM armhfbuild/nginx
LABEL Name=tuttas/pollclient Version=0.0.1
ENV SECRET 1234
ENV PORT :3000/
ENV HOST window.location.hostname
RUN mkdir -p /usr/share/nginx/html/assets
COPY Client/dist /usr/share/nginx/html
COPY Client/dist/assets /usr/share/nginx/html/assets
COPY client-startup.sh /usr/share
RUN chmod +x /usr/share/client-startup.sh
CMD sh -C "/usr/share/client-startup.sh" $HOST $PORT $SECRET
