
### Neuen Umfrageteilnehmer eintragen (Felder _id,course und poll sind Pflichtfelder)
POST http://{{host}}:3000/quest/ HTTP/1.1
Content-Type: application/json 
secret: 1234

{
    "_id": "abcdef",
    "course": "FIAE17J",
    "poll": "Umfrage1",
    "email": "fiae17j.mmusterm@mm-bbs.de"
}

### bisherige Antworten des Teilnehmes abfragen
GET http://{{host}}:3000/quest/abcd HTTP/1.1
secret: 1234

### Antwort eines Teilnehmes eintragen
PUT http://{{host}}:3000/quest/ HTTP/1.1
Content-Type: application/json
secret: 1234

{
    "_id": "abcd",
    "question": "Frage5",
    "answer": 4
}

### Abfragen der Klassen einer Umfrage
GET http://{{host}}:3000/courses/Umfrage1 HTTP/1.1
Content-Type: application/json
secret: 1234

### Abfragen aller Umfragen
GET http://{{host}}:3000/polls/ HTTP/1.1
Content-Type: application/json
secret: 1234

### Abfragen aller Fragen
GET http://{{host}}:3000/questions/ HTTP/1.1
Content-Type: application/json
secret: 1234

### Auswertung abfragen
GET http://{{host}}:3000/evaluate/Umfrage1/FIAE1 HTTP/1.1
Content-Type: application/json
secret: 1234
